config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  scope '/blog' do
    resources :articles
  end
  root to: 'main#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  #match '*path', :to => 'application#not_found', via: [:get, :post]
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  has_one_attached :main_img
  has_rich_text :body


  def full_keywords(count_keys = 1, min_length_word = 4)
    if body.to_plain_text.length > 1
      array_keywords = []
      array_keywords = body.to_plain_text&.gsub(/[^[:word:]]/, ' ')&.downcase&.split(' ')
      array_keywords.compact!
      index_hash = {}
      array_keywords.each do |word|
        if word.length > min_length_word
          index_hash[word] ? index_hash[word] += 1 : index_hash[word] = 1
        end
      end
      array_keywords = []
      index_hash.each do |key, value|
        array_keywords << { key => value }
      end
      array_keywords.sort { |x, y| y.values[0] <=> x.values[0] }[0..count_keys - 1].map { |t| t.keys.first }
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(all_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(all_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :main_img)
    end

  def all_params
    rez = article_params
    rez[:user_id] = current_user.id
    rez
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def url_for_image(object)
    extract_color = nil
    object.blob.open() do |file|
      image = MiniMagick::Image.open(file.path)
      image.resize "1x1"
      pixels = image.get_pixels
      extract_color = '#' + pixels[0][0].map{|p| p.to_s(16)}.join.upcase

    end
    url_for(
        object.variant(
            combine_options: {
                resize: "x300",
                gravity: "North",
                background: extract_color,
                extent: '600x600',
            }
        )
    )

  end
end

app/views/articles/_form.html.slim
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    h2
      = pluralize(article.errors.count, "error")
      |  prohibited this article from being saved:
    ul
      - article.errors.full_messages.each do |message|
        li
          = message
  .form-group
    = form.label 'Заголовок', for: :article_title
    = form.text_field :title, class: 'form-control'
  .form-group
    = form.label 'Картинка на главную страницу', for: :article_main_img
    = form.file_field :main_img, class: 'form-control'
  .form-group
    = form.label 'Текст статьи', for: :article_body
    = form.rich_text_area :body
  .form-group
    = form.submit

app/views/articles/edit.html.slim
h1
  | Editing Article
= render 'form', article: @article
= link_to 'Show', @article
|  | 
= link_to 'Back', articles_path

app/views/articles/index.html.slim
p#notice
  = notice
h1
  | Articles
table
  thead
    tr
      th
        | Title
      th
        | Body
      th[colspan="3"]
  tbody
    - @articles.each do |article|
      tr
        td
          = article.title
        td
          = article.body
        td
          = link_to 'Show', article
        td
          = link_to 'Edit', edit_article_path(article)
        td
          = link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Article', new_article_path

app/views/articles/new.html.slim
h2.text-center
  | Новая статья
= render 'form', article: @article
= link_to 'Back', articles_path

app/views/articles/show.html.slim
- content_for :title, @article.title
h1.text-center
  = @article.title
p
  = render inline: @article.body